BOT_TOKEN=your_bot_token_here
ADMIN_ID=your_admin_id_here
CHANNEL_ID=your_channel_id_here
CHANNEL_USERNAME=your_channel_username_here

FIREBASE_PROJECT_ID=your_firebase_project_id
FIREBASE_PRIVATE_KEY=your_firebase_private_key
FIREBASE_CLIENT_EMAIL=your_firebase_client_emaiI

PAYMENT_WEEK=your_payment_week_link
PAYMENT_MONTH=your_payment_month_link
PAYMENT_3MONTHS=your_payment_3months_link
PAYMENT_YEAR=your_payment_year_link

IMGBB_API_KEY=your_imgbb_api_key